spring:
  application:
    name: discovery-service
server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
